//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class estoque
    {
        public string item { get; set; }
        public decimal quantidade { get; set; }
        public string movimentacao { get; set; }
        public int id { get; set; }
    }
}
