//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcionario
    {
        public string nome { get; set; }
        public string telefone { get; set; }
        public string cpf { get; set; }
        public System.DateTime dataNascimento { get; set; }
        public string rua { get; set; }
        public string numero { get; set; }
        public string bairro { get; set; }
        public string uf { get; set; }
        public string cidade { get; set; }
        public string complemento { get; set; }
        public string cargo { get; set; }
    }
}
