//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresaAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pro_chefeEntities : DbContext
    {
        public pro_chefeEntities()
            : base("name=pro_chefeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<delivery> delivery { get; set; }
        public virtual DbSet<delivery_produto> delivery_produto { get; set; }
        public virtual DbSet<estoque> estoque { get; set; }
        public virtual DbSet<funcionario> funcionario { get; set; }
        public virtual DbSet<ingrediente> ingrediente { get; set; }
        public virtual DbSet<mesa> mesa { get; set; }
        public virtual DbSet<produto> produto { get; set; }
        public virtual DbSet<produto_ingrediente> produto_ingrediente { get; set; }
        public virtual DbSet<produto_mesa> produto_mesa { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
