//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresaAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto_ingrediente
    {
        public int id_produto { get; set; }
        public int id_ingrediente { get; set; }
        public decimal quantidade { get; set; }
    
        public virtual ingrediente ingrediente { get; set; }
        public virtual produto produto { get; set; }
    }
}
